apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

#namePrefix: dev-
commonLabels:
  variant: development


# replace the image tag of the container with latest
images:
- digest: sha256:214bf503afe0b6a4db637a018b9db7a483c1fbbdd780703d33fac6c36823eb13
  name: quay.io/ksobkowiak/person-service:latest
  newName: quay.io/ksobkowiak/person-service:latest

# generate a configmap 
configMapGenerator:
- literals:
  - APP_GREETING=Hello gitOps interested people! Hope you like it!
  name: app-config

# This patch provides the name of the namespace into the env-value of the Job
# This is needed because we want to call the target rest service of person-service
# which is: person-service.$NAMESPACE.svc:8080
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: person-dev
  target:
    kind: Job
