apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  org: wanja.org
  app.kubernetes.io/part-of: person-service

resources:
- service.yaml
- secret.yaml
- deploymentconfig.yaml