kind: Service
apiVersion: v1
metadata:
  name: wanjaserver
spec:
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
  sessionAffinity: None
  selector:
    name: wanjaserver